module.exports = {
  MAX_KEYS_PER_BATCH_GET: 100,
  MAX_ITEMS_PER_BATCH_WRITE: 25,
  UNPROCESSED_ITEMS_RETRY_LIMIT: 2,
  DEFAULT_UNPROCESSED_ITEMS_MIN_RETRY_TIMOUT_MS: 300,
  DEFAULT_UNPROCESSED_ITEMS_MAX_RETRY_TIMOUT_MS: 1000
};
